---
- hosts: localhost
  name: Volume Action
  collections:
    - netapp.ontap
  gather_facts: false
  vars_files:
    ./vars.yml
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver: "{{ vserver }}"
      aggr:     "{{ aggr }}"
      https: true
      validate_certs: false
    parent_vol_name: project_A_workspace_volume_1
    clone_vol_name:  project_A_workspace_volume_1_clone
    parent_snapshot: 
    junction_name: workspace_volume_1_clone
    junction_root_path: project_A

  tasks:
  - name: Clone Existing Workspace Volume
    na_ontap_volume_clone:
      state: present
      parent_volume: "{{ parent_vol_name }}"
      #parent_snapshot: "{{ parent_snapshot }}"
      volume: "{{ clone_vol_name }}"
      uid: "1000"
      gid: "1000"
      junction_path: "/{{ junction_root_path }}/{{ junction_name }}"
      space_reserve: none
      vserver: "{{ vserver }}"
      <<: *login

#  - name: Populate worksapce with files
#    git:
#      repo: http://github.com/mjmotojohnson/ansible_codeeasy.git
#      dest: /{{ junction_root_path }}/{{ junction_name }}
#      clone: yes
#      update: yes
#      force: yes

# Mount the workspace volume 
#   Note no need to mount the project workspace volume.  It will auto-magically
#   get mounted via the junction_root_path.  It is assume the junction_root
#   volume has already been mounted.
#
# Mount project root volume - see volume.yml  
# %> mkdir /project_A
# %> mount -o "vers=3,rw,bg,hard,rsize=65536,wsize=65536,proto=tcp,intr,timeo=600" 192.168.0.131:/project_A_root_volume /project_A
#
#
