---
- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: false
  vars_files:
    ./vars.yml
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver:  "{{ vserver }}"
      aggr:     "{{ aggr }}"
      https: true
      validate_certs: false

- name: create volume clone
  na_ontap_volume_clone:
    state=present
    parent_volume={{ partent_volume_name }}
    volume={{ clone_volume_name }}
    space_reserve=none
    parent_snapshot={{ snapshot_name }}
    <<: *login
