---
- hosts: localhost
  gather_facts: false
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
- name: create volume clone
  na_ontap_volume_clone:
    state=present
    username=admin
    password=netapp1!
    hostname=10.193.74.27
    vserver: "{{ vserver }}"
    parent_volume={{ partent_volume_name }}
    volume={{ clone_volume_name }}
    space_reserve=none
    parent_snapshot={{ snapshot_name }}
    <<: *login
