---
- hosts: localhost
  name: Volume Action
  collections:
    - netapp.ontap
  gather_facts: false
  vars_files:
    ./vars.yml
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver:  "{{ vserver }}"
      aggr:     "{{ aggr }}"
      https: true
      validate_certs: false
    vol_name: project_A_root_volume
    junction_root_path: project_A
    
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      size: 1
      space_guarantee: none
      size_unit: gb
      policy: default
      junction_path: "/{{ junction_root_path }}"
      <<: *login

# Mount the volume manually 
#   Note the mount host data IP (LIF) is different than the storage management IP. 
# %> mkdir /project_A
# %> mount -o "vers=3,rw,bg,hard,rsize=65536,wsize=65536,proto=tcp,intr,timeo=600" 192.168.0.131:/project_A /project_A
#
#
