---
- hosts: localhost
  name: Volume Action
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: openstack
    aggr: aggr1
    vol_name: ansibleVol
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 40
      size_unit: gb
      policy: default
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

# Mount the volume manually 
#   Note the mount host data IP (LIF) is different than the storage management IP. 
# %> mkdir /foo
# %> mount -o "vers=3,rw,bg,hard,rsize=65536,wsize=65536,proto=tcp,intr,timeo=600" 192.168.0.131:/ansibleVol /foo
#
#
